### ISSUE TITLE
SFTP no longer accepting RSA key

### ISSUE THREAD

**Issue by markmonroy** [hassio-addons/addon-ssh#354] opened 2021-12-18 15:32 UTC
# Problem/Motivation

SFTP no longer accepting RSA key after 10.0.0 update

## Expected behavior

Expected SFTP to continue to work

## Actual behavior

SFTP stopped working

## Steps to reproduce

Update addon to 10.0.0, no config changes, SSH still works, but SFTP rejects my ssh-rsa key as "not in PubkeyAcceptedAlgorithms." Using macOS Transmit 5.8.2 as my client.

```
Connection from 192.168.1.XX port 51234 on 192.168.1.XX port 22 rdomain ""
userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
userauth_pubkey: key type ssh-dss not in PubkeyAcceptedAlgorithms [preauth]
userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
userauth_pubkey: key type ssh-dss not in PubkeyAcceptedAlgorithms [preauth]
maximum authentication attempts exceeded for root from 192.168.1.XXport 51234 ssh2 [preauth]
Disconnecting authenticating user root 192.168.1.XX port 51234: Too many authentication failures [preauth]
```

Compared to successful command line SSH from the same computer:

```
Connection from 192.168.1.XX port 51487 on 192.168.1.XX port 22 rdomain ""
Accepted key RSA SHA256:XXXXXXX found at /etc/ssh/authorized_keys:1
Postponed publickey for root from 192.168.1.XX port 51487 ssh2 [preauth]
Accepted key RSA SHA256:XXXXXXX found at /etc/ssh/authorized_keys:1
Accepted publickey for root from 192.168.1.XX port 51487 ssh2: RSA SHA256: XXXXXXX
Starting session: shell on pts/0 for root from 192.168.1.XX port 51487 id 0
```

My config:

```
init_commands: []
packages: []
share_sessions: false
ssh:
  allow_agent_forwarding: false
  allow_remote_port_forwarding: false
  allow_tcp_forwarding: false
  authorized_keys:
    - >-
      ssh-rsa
      XXXXX
    - >-
      ssh-rsa 
      XXXXX
  compatibility_mode: false
  password: ''
  sftp: true
  username: root
zsh: false

```

**Comment by markmonroy** [comment] 2021-12-18 16:25
As a workaround I generated a new ed25519 key just for Transmit and I'm now able to log in.

**Comment by CreasaBE** [comment] 2021-12-18 19:06
same issue here..
manually editing /etc/ssh/sshd_config and adding
PubkeyAcceptedKeyTypes=+ssh-rsa 

fixes the issue temporarily until the config is edited through the webui

**Comment by TroelsS** [comment] 2021-12-20 18:50
Same issue here, after update to 10.0.0 I get this in the log:
userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]

**Comment by realthk** [comment] 2021-12-21 12:40
Same here, cannot login with Putty/WinSCP any more (with key generated by PuttyGen). 
No problem from Linux terminal though.
Reverted back to 9.1.1, that still works fine with Putty.

**Comment by darootler** [comment] 2021-12-22 09:04
Same issue here, is there a command available to downgrade the add-on?

Regards
Richard

**Comment by CreasaBE** [comment] 2021-12-22 09:07
> Same issue here, is there a command available to downgrade the add-on?
> 
> Regards Richard

you can use a workaround if you don't edit the config. through the webconsole you can edit /etc/ssh/sshd_config file. See my reply above to see the line that you need to add.
but it'll only work until you edit the config again as that will reset the sshd_config file to default again

**Comment by darootler** [comment] 2021-12-22 09:10
> PubkeyAcceptedKeyTypes=+ssh-rsa

Unfortunately this workaround does not work for me.

Regards
Richard

**Comment by CreasaBE** [comment] 2021-12-22 09:12
> > PubkeyAcceptedKeyTypes=+ssh-rsa
> 
> Unfortunately this workaround does not work for me.
> 
> Regards Richard
sorry, forget to add that you need to restart ssh too via "service sshd restart"

**Comment by darootler** [comment] 2021-12-22 09:24
No way for me, this is my config:

![image](https://user-images.githubusercontent.com/11849583/147069100-39f7273b-0f0f-4e9f-b899-d420cd16f315.png)

Even after restarting sshd i am not able to connect.

Regards
Richard
Richard

**Comment by frenck** [comment] 2022-01-07 19:13
This is caused by an upstream change: https://www.openssh.com/txt/release-8.8

```
Potentially-incompatible changes
================================

This release disables RSA signatures using the SHA-1 hash algorithm
by default. This change has been made as the SHA-1 hash algorithm is
cryptographically broken, and it is possible to create chosen-prefix
hash collisions for <USD$50K [1]

For most users, this change should be invisible and there is
no need to replace ssh-rsa keys. OpenSSH has supported RFC8332
RSA/SHA-256/512 signatures since release 7.2 and existing ssh-rsa keys
will automatically use the stronger algorithm where possible.

Incompatibility is more likely when connecting to older SSH
implementations that have not been upgraded or have not closely tracked
improvements in the SSH protocol. For these cases, it may be necessary
to selectively re-enable RSA/SHA1 to allow connection and/or user
authentication via the HostkeyAlgorithms and PubkeyAcceptedAlgorithms
options. For example, the following stanza in ~/.ssh/config will enable
RSA/SHA1 for host and user authentication for a single destination host:

    Host old-host
        HostkeyAlgorithms +ssh-rsa
	PubkeyAcceptedAlgorithms +ssh-rsa

We recommend enabling RSA/SHA1 only as a stopgap measure until legacy
implementations can be upgraded or reconfigured with another key type
(such as ECDSA or Ed25519).

[1] "SHA-1 is a Shambles: First Chosen-Prefix Collision on SHA-1 and
    Application to the PGP Web of Trust" Leurent, G and Peyrin, T
    (2020) https://eprint.iacr.org/2020/014.pdf
```

Considering the reasoning for that change and the written solutions in that release note, I think we can close this.

**Closed by frenck** 2022-01-07 19:13 UTC

**Comment by darootler** [comment] 2022-01-07 20:41
I just regenerated the keypair with ecdsa-sha2-nistp521 and everything is working fine with version 10.0.1.

@frenck 

Thank you for pointing that out.

Regards
Richard

**Comment by realthk** [comment] 2022-01-08 17:46
Yes, key regenerated with PuttyGen updated to the latest 0.76 version also works, thanks.
