### ISSUE TITLE
[FATAL tini (7)] exec /init failed: Exec format error

### ISSUE THREAD

**Issue by P-Verbrugge** [hassio-addons/addon-ssh#105] opened 2019-12-18 12:28 UTC
# Problem/Motivation

Updated the addon from version  6.4.1 to 6.4.2

## Expected behavior

I would expect the terminal addon to run the same way it did before the update, with the same config.

## Actual behavior

The addon will not start anymore and reports the error: [FATAL tini (7)] exec /init failed: Exec format error

## Steps to reproduce

Install hassio in a docker enviroment using Rasbian Buster. Install the older version of the terminal app and make sure it works. Upgrade from version 6.4.1 to version 6.4.2.

**Comment by frenck** [comment] 2019-12-18 12:29
Please be sure to check the issue that are here, before opening a new one.
Duplicate of #93.

It has been resolved and documented in #93.

**Closed by frenck** 2019-12-18 12:29 UTC

**Comment by P-Verbrugge** [comment] 2019-12-18 12:35
@frenck Whoops. Sorry. I didn't notice the closed tickets. I wil keep it in mind the next time.

**Comment by frenck** [comment] 2019-12-18 12:37
No problem m8!
