### ISSUE TITLE
I have a Raspberry PI3 B+, connected to a SSD hard drive for startup and it works perfect. However as is known memory is an issue on 3 B+.

### ISSUE THREAD

**Issue by pwandel** [hassio-addons/addon-ssh#555] opened 2023-05-02 14:56 UTC
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by pwandel** [comment] 2023-05-02 15:02
Now Franck gave in history a perfect instruction to create and use a swap file in SSH-terminal. It works very good.
The point is that after every update I have to remove this line for an error free startup and than after startup of SSH insert and restart the SSH again.

**** Init command SSH terminal when swap file disappears
init_commands:
- >-
    if [ ! -f /backup/_swap.swap ]; then fallocate -l 4G /backup/_swap.swap &&
    mkswap /backup/_swap.swap && chmod 0600 /backup/_swap.swap && swapon
    /backup/_swap.swap ; elif [[ ! $(dmesg|grep _swap.swap) = *swap\ on* ]] ;
    then swapon /backup/_swap.swap ; else swapon /backup/_swap.swap ; fi

Is there a command, to make the init command optional?

Kind regards

**Comment by frenck** [comment] 2023-05-04 12:05
Swap file management is not an addon task. This is also not a bug report with the addon so going to close it on this end.

../Frenck

**Closed** 2023-05-04 12:05 UTC
