### ISSUE TITLE
No matching key exchange method found

### ISSUE THREAD

**Issue by bwohlgamuth** [hassio-addons/addon-ssh#4] opened 2017-10-08 23:20 UTC
Trying to connect from an iOS app called Textastic via sftp. Failure I’m seeing in the add on log is:

no matching key exchange method found. Their offer: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1 [preauth]

I don’t have much in the way of configuration on the iOS side, is there any configuration available on the add on side to get this working?

**Comment by frenck** [comment] 2017-10-11 20:34
This is not an issue with the add-on perse. This is caused by the client you are using.
The SSH daemon in this add-on is configured with security in mind and is therefore not supporting any ciphers that contain possible weaknesses.

There is currently no way of bypassing this, so maybe I should add this an option?

**Comment by bwohlgamuth** [comment] 2017-10-11 20:37
I’d be a fan of that option. I think it’d be a good workaround for a situation like this where one has minimal control over the ciphers supported by the client.

**Comment by frenck** [comment] 2017-10-11 20:41
I've added it to the roadmap for v2.0.0

**Comment by bwohlgamuth** [comment] 2017-10-11 21:22
Awesome! Do you have any idea when that’ll be available?

**Comment by frenck** [comment] 2017-10-11 23:21
I know you'd like an answer to that question, but you'll have to realize I do this all in my spare time. Therefore I'm unable to answer that question. I'll do my best.

**Comment by bwohlgamuth** [comment] 2017-10-11 23:23
Totally reasonable. I really appreciate the add on, and you considering this additional functionality.

**Comment by frenck** [comment] 2017-10-20 08:19
@bwohlgamuth Feature has been build and merged into master.
The next release will introduce a `compatibility_mode` configuration option.

**Closed by frenck** 2017-10-20 08:19 UTC
Labels: Accepted, Feature, Medium Priority, RFC
