### ISSUE TITLE
How do you actually configure Mosh ? 

### ISSUE THREAD

**Issue by johntdyer** [hassio-addons/addon-ssh#502] opened 2023-03-11 19:10 UTC
# Problem/Motivation

It says Mosh is supported, but it doesnt have any information on how to configure the server or anything... Is this just a gap in docs or am I misunderstanding the support?

## Expected behavior

to be able to configure mosh

## Actual behavior

cant use mosh

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment] 2023-03-11 20:11
Just install mosh client (or compatible) on your machine and connect to the adding using that instead of the ssh client. Done.

🤷

**Comment by tagno25** [comment] 2023-04-08 21:57
@johntdyer Make sure you are using this community addon, and not the official "Terminal & SSH" addon.

**Comment by frenck** [comment] 2023-04-11 08:12
Alright, going to close this issue, as it is not a bug report but a support question.

../Frenck

**Closed by frenck** 2023-04-11 08:12 UTC
