### ISSUE TITLE
SSH Connection Prompt Issue and Missing Welcome Screen in Home Assistant

### ISSUE THREAD

**Issue by masfernandez** [hassio-addons/addon-ssh#805] opened 2024-10-21 20:23 UTC
# Problem/Motivation

> 
While connecting to Home Assistant via SSH, the connection is established, but strange symbols appear in the terminal prompt. Additionally, the normal Home Assistant welcome screen does not appear immediately upon login.

## Expected behavior

> 
Upon connecting to Home Assistant via SSH, the regular Home Assistant welcome screen should appear, and the terminal prompt should display normally without any unusual characters or symbols.

## Actual behavior

> 
After connecting via SSH, the terminal prompt shows strange symbols instead of the usual prompt. Also, the regular Home Assistant welcome screen does not appear automatically. I need to run sudo -i to fix the prompt and get the Home Assistant welcome screen to display properly.

## Steps to reproduce

>
1. Open an SSH connection to a Home Assistant instance.
2. Observe the terminal prompt for strange symbols.
3. Note that the regular Home Assistant welcome screen does not appear.
4. Run sudo -i to make the Home Assistant welcome screen appear and fix the prompt.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

## Screenshot:

<img width="843" alt="Captura de pantalla 2024-10-21 a las 22 15 18" src="https://github.com/user-attachments/assets/7004e3ff-7b25-4a0f-8bd0-53e0be184d32">

**Comment by sinclairpaul** [comment] 2024-10-21 20:35
Duplicate of #788

**Closed by sinclairpaul** 2024-10-21 20:35 UTC
