### ISSUE TITLE
Add-on can't start sshd

### ISSUE THREAD

**Issue by izipuho** [hassio-addons/addon-ssh#669] opened 2023-12-30 07:27 UTC
# Problem/Motivation

> I want to start add-on, but it fails with no obvious reason (for me).

## Expected behavior

> Working add-on. :-)

## Actual behavior

> It keeps starting but failing at sshd starting point:
```
 System: Armbian 23.11.1 bookworm  (aarch64 / odroid-c2)
 Home Assistant Core: 2023.12.4
 Home Assistant Supervisor: 2023.12.1.dev1903
------------------------------------------------------—--
.....
[10:14:32] INFO: Starting the ttyd daemon...
[10:14:32] INFO: Starting the SSH daemon...
Bind to port 22 on 0.0.0.0 failed: Address in use.
Bind to port 22 on :: failed: Address in use.
Cannot bind any address.
[10:14:32] INFO: Service SSH exited with code 255 (by signal 0)
```
> and it stops everything after that

## Steps to reproduce

> Install, start.

**Comment by frenck** [comment] 2023-12-30 08:36
> Bind to port 22 on 0.0.0.0 failed: Address in use.
Bind to port 22 on :: failed: Address in use.

The error says it all. Port 22 is already in use on your system. You have to either free it up by moving what you have installed/active currently on port 22 or change the port of the SSH add-on network setting to something else.

Closing, as this is not a bug.

../Frenck

**Closed** 2023-12-30 08:36 UTC
